In [1]:
import json
import pandas as pd
import regex as re

data = [json.loads(line) for line in open('farmers-protest-tweets-2021-03-5.json', 'r')]

In [2]:
# Flatten data
df_nested_list = pd.json_normalize(data)

In [3]:
df_nested_list

,url,date,content,renderedContent,id,outlinks,tcooutlinks,replyCount,retweetCount,likeCount,...,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quoteCount,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.conversationId,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.lang,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.source,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceUrl,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceLabel,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.media,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.retweetedTweet,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.mentionedUsers
0,https://twitter.com/ShashiRajbhar6/status/1376...,2021-03-30T03:33:46+00:00,Support üëá\n\n#FarmersProtest,Support üëá\n\n#FarmersProtest,1376739399593910273,[],[],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://twitter.com/kaursuk06272818/status/137...,2021-03-30T03:33:23+00:00,Supporting farmers means supporting our countr...,Supporting farmers means supporting our countr...,1376739306287427584,[],[],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://twitter.com/kaursuk06272818/status/137...,2021-03-30T03:31:00+00:00,Support farmers if you are related to food #St...,Support farmers if you are related to food #St...,1376738704128020488,[],[],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://twitter.com/SukhdevSingh_/status/13767...,2021-03-30T03:30:45+00:00,#StopHateAgainstFarmers support #FarmersProtes...,#StopHateAgainstFarmers support #FarmersProtes...,1376738640542400518,[],[],0,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://twitter.com/Davidmu66668113/status/137...,2021-03-30T03:30:30+00:00,"You hate farmers I hate you, \nif you love the...","You hate farmers I hate you, \nif you love the...",1376738579171344386,[],[],0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419502,https://twitter.com/TeamSOOUDA/status/13560306...,2021-02-01T00:04:26+00:00,We are calling on leaders to speak up against ...,We are calling on leaders to speak up against ...,1356030613912870916,[],[],0,3,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419503,https://twitter.com/VibhaBurman/status/1356030...,2021-02-01T00:04:16+00:00,Powerüí™üèª of panchayat but our government still ...,Powerüí™üèª of panchayat but our government still ...,1356030569709113346,[https://twitter.com/KisanEktaMarch/status/135...,[https://t.co/PKNn3pWS1Q],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419504,https://twitter.com/NavJammu/status/1356029858...,2021-02-01T00:01:26+00:00,@AmrinderSingh__ @CNN @cnni I‚Äôm coming to term...,@AmrinderSingh__ @CNN @cnni I‚Äôm coming to term...,1356029858699046912,[],[],0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419505,https://twitter.com/Atwal72/status/13560296726...,2021-02-01T00:00:42+00:00,What about the peaceful protests in Delhi........,What about the peaceful protests in Delhi........,1356029672614719492,[https://twitter.com/LBCNews/status/1356020563...,[https://t.co/JtzHBmm6YH],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419506,https://twitter.com/Manjind22050118/status/135...,2021-02-01T00:00:07+00:00,This is the award government is giving to the ...,This is the award government is giving to the ...,1356029524216057858,[],[],0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Pregunta 1

### Los top 10 tweets m√°s retweet

In [8]:
def pregunta_1(df):
    retweet_top = df.sort_values(by=['retweetCount'], ascending=False)
    return retweet_top.head(10)

pregunta_1(df_nested_list)

,url,date,content,renderedContent,id,outlinks,tcooutlinks,replyCount,retweetCount,likeCount,...,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quoteCount,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.conversationId,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.lang,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.source,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceUrl,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceLabel,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.media,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.retweetedTweet,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.mentionedUsers
408128,https://twitter.com/rihanna/status/13566258896...,2021-02-02,why aren‚Äôt we talking about this?! #FarmersPro...,why aren‚Äôt we talking about this?! #FarmersPro...,1356625889602199552,[https://www.cnn.com/2021/02/01/asia/india-int...,[https://t.co/obmIlXhK9S],163065,315547,944307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395142,https://twitter.com/GretaThunberg/status/13566...,2021-02-02,We stand in solidarity with the #FarmersProtes...,We stand in solidarity with the #FarmersProtes...,1356694884615340037,[https://www.cnn.com/2021/02/01/asia/india-int...,[https://t.co/tqvR0oHgo0],49793,103957,319363,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266196,https://twitter.com/GretaThunberg/status/13572...,2021-02-04,I still #StandWithFarmers and support their pe...,I still #StandWithFarmers and support their pe...,1357282507616645122,[],[],39596,67694,234676,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366579,https://twitter.com/miakhalifa/status/13568483...,2021-02-03,"‚ÄúPaid actors,‚Äù huh? Quite the casting director...","‚ÄúPaid actors,‚Äù huh? Quite the casting director...",1356848397899112448,[],[],15569,35921,139959,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372793,https://twitter.com/miakhalifa/status/13568277...,2021-02-03,What in the human rights violations is going o...,What in the human rights violations is going o...,1356827705161879553,[],[],9082,26972,99227,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314192,https://twitter.com/TeamJuJu/status/1357048037...,2021-02-03,"Happy to share that I‚Äôve donated $10,000 to pr...","Happy to share that I‚Äôve donated $10,000 to pr...",1357048037302960129,[https://www.usnews.com/news/world/articles/20...,[https://t.co/0WoEw0l3ij],7683,23251,59248,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215034,https://twitter.com/BobBlackman/status/1357755...,2021-02-05,There has been much social media coverage arou...,There has been much social media coverage arou...,1357755699162398720,[],[],1845,20132,42779,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398011,https://twitter.com/vanessa_vash/status/135668...,2021-02-02,Farmers feed the world. Fight for them. Protec...,Farmers feed the world. Fight for them. Protec...,1356681136655769605,[],[],1301,18744,67986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325261,https://twitter.com/kylekuzma/status/135700972...,2021-02-03,Should be talking about this! #FarmersProtest\...,Should be talking about this! #FarmersProtest\...,1357009721090138112,[https://www.cnn.com/2021/02/01/asia/india-int...,[https://t.co/Xh09iTvVoF],4167,17368,39653,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163689,https://twitter.com/AmandaCerny/status/1359013...,2021-02-09,To all of my influencer/celeb friends- read up...,To all of my influencer/celeb friends- read up...,1359013362881994752,[],[],2028,15677,81375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Pregunta 2

### Los top 10 usuarios en funci√≥n a la cantidad de tweets que emitieron

In [9]:
def pregunta_2(df):
    usuarios_top = df['user.username'].value_counts()
    return usuarios_top[:10]

pregunta_2(df_nested_list)

harjot_tweeting    7134
tasveersandhu      2091
shells_n_petals    1991
jot__b             1841
rebelpacifist      1806
rumsomal           1722
Iamjazzie96        1502
Jass_k_G           1460
DigitalKisanBot    1453
z_khalique007      1446
Name: user.username, dtype: int64

## Pregunta 3

### Los top 10 d√≠as donde hay m√°s tweets

In [10]:
def pregunta_3(df):
    df_new = df.copy()
    df_new['date'] = df['date'].apply(lambda x: x[:10])
    dias_top = df_new['date'].value_counts()
    return dias_top[:10]

pregunta_3(df_nested_list)

2021-02-03    83866
2021-02-04    58607
2021-02-05    33332
2021-02-02    28548
2021-02-06    22420
2021-02-07    11325
2021-02-09     9320
2021-02-08     8920
2021-02-10     7973
2021-02-11     5698
Name: date, dtype: int64

## Pregunta 4

### Top 10 hashtags m√°s usados

In [13]:
def pregunta_4(df):
    df_new = df.copy()
    df_new['hashtags'] = df['content'].apply(lambda x: re.findall(r"#(\w+)", x))
    return df_new.explode('hashtags')['hashtags'].value_counts()[:10]

pregunta_4(df_nested_list)

FarmersProtest              406613
IStandWithFarmers            15783
farmersprotest               15458
IndianFarmersHumanRights     12019
FarmersAreIndia              11043
StandWithFarmers             10645
Rihanna                       9117
FarmersProtests               8750
Farmers                       6561
shameonbollywood              6270
Name: hashtags, dtype: int64

In [14]:
def Main(df):
    respuesta_1 = pregunta_1(df)
    respuesta_2 = pregunta_2(df)
    respuesta_3 = pregunta_3(df)
    respuesta_4 = pregunta_4(df)
    print("Respuesta a preunta 1: ", respuesta_1)
    print("-------------------------------------")
    print("Respuesta a pregunta 2: ", respuesta_2)
    print("-------------------------------------")
    print("Respuesta a pregunta 3: ", respuesta_3)
    print("-------------------------------------")
    print("Respuesta a pregunta 4: ", respuesta_4)

In [15]:
Main(df_nested_list)

Respuesta a preunta 1:                                                        url        date  \
408128  https://twitter.com/rihanna/status/13566258896...  2021-02-02
395142  https://twitter.com/GretaThunberg/status/13566...  2021-02-02
266196  https://twitter.com/GretaThunberg/status/13572...  2021-02-04
366579  https://twitter.com/miakhalifa/status/13568483...  2021-02-03
372793  https://twitter.com/miakhalifa/status/13568277...  2021-02-03
314192  https://twitter.com/TeamJuJu/status/1357048037...  2021-02-03
215034  https://twitter.com/BobBlackman/status/1357755...  2021-02-05
398011  https://twitter.com/vanessa_vash/status/135668...  2021-02-02
325261  https://twitter.com/kylekuzma/status/135700972...  2021-02-03
163689  https://twitter.com/AmandaCerny/status/1359013...  2021-02-09

                                                  content  \
408128  why aren‚Äôt we talking about this?! #FarmersPro...
395142  We stand in solidarity with the #FarmersProtes...
266196  I still #StandWithFarmers and support their pe...
366579  ‚ÄúPaid actors,‚Äù huh? Quite the casting director...
372793  What in the human rights violations is going o...
314192  Happy to share that I‚Äôve donated $10,000 to pr...
215034  There has been much social media coverage arou...
398011  Farmers feed the world. Fight for them. Protec...
325261  Should be talking about this! #FarmersProtest\...
163689  To all of my influencer/celeb friends- read up...

                                          renderedContent  \
408128  why aren‚Äôt we talking about this?! #FarmersPro...
395142  We stand in solidarity with the #FarmersProtes...
266196  I still #StandWithFarmers and support their pe...
366579  ‚ÄúPaid actors,‚Äù huh? Quite the casting director...
372793  What in the human rights violations is going o...
314192  Happy to share that I‚Äôve donated $10,000 to pr...
215034  There has been much social media coverage arou...
398011  Farmers feed the world. Fight for them. Protec...
325261  Should be talking about this! #FarmersProtest\...
163689  To all of my influencer/celeb friends- read up...

                         id  \
408128  1356625889602199552
395142  1356694884615340037
266196  1357282507616645122
366579  1356848397899112448
372793  1356827705161879553
314192  1357048037302960129
215034  1357755699162398720
398011  1356681136655769605
325261  1357009721090138112
163689  1359013362881994752

                                                 outlinks  \
408128  [https://www.cnn.com/2021/02/01/asia/india-int...
395142  [https://www.cnn.com/2021/02/01/asia/india-int...
266196                                                 []
366579                                                 []
372793                                                 []
314192  [https://www.usnews.com/news/world/articles/20...
215034                                                 []
398011                                                 []
325261  [https://www.cnn.com/2021/02/01/asia/india-int...
163689                                                 []

                      tcooutlinks  replyCount  retweetCount  likeCount  ...  \
408128  [https://t.co/obmIlXhK9S]      163065        315547     944307  ...
395142  [https://t.co/tqvR0oHgo0]       49793        103957     319363  ...
266196                         []       39596         67694     234676  ...
366579                         []       15569         35921     139959  ...
372793                         []        9082         26972      99227  ...
314192  [https://t.co/0WoEw0l3ij]        7683         23251      59248  ...
215034                         []        1845         20132      42779  ...
398011                         []        1301         18744      67986  ...
325261  [https://t.co/Xh09iTvVoF]        4167         17368      39653  ...
163689                         []        2028         15677      81375  ...

        quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quoteCount  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

        quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.conversationId  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

       quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.lang  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

       quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.source  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

       quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceUrl  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

       quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceLabel  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

       quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.media  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

       quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.retweetedTweet  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

        quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet  \
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

       quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.mentionedUsers
408128                                                NaN
395142                                                NaN
266196                                                NaN
366579                                                NaN
372793                                                NaN
314192                                                NaN
215034                                                NaN
398011                                                NaN
325261                                                NaN
163689                                                NaN

[10 rows x 328 columns]
-------------------------------------
Respuesta a pregunta 2:  harjot_tweeting    7134
tasveersandhu      2091
shells_n_petals    1991
jot__b             1841
rebelpacifist      1806
rumsomal           1722
Iamjazzie96        1502
Jass_k_G           1460
DigitalKisanBot    1453
z_khalique007      1446
Name: user.username, dtype: int64
-------------------------------------
Respuesta a pregunta 3:  2021-02-03    83866
2021-02-04    58607
2021-02-05    33332
2021-02-02    28548
2021-02-06    22420
2021-02-07    11325
2021-02-09     9320
2021-02-08     8920
2021-02-10     7973
2021-02-11     5698
Name: date, dtype: int64
-------------------------------------
Respuesta a pregunta 4:  FarmersProtest              406613
IStandWithFarmers            15783
farmersprotest               15458
IndianFarmersHumanRights     12019
FarmersAreIndia              11043
StandWithFarmers             10645
Rihanna                       9117
FarmersProtests               8750
Farmers                       6561
shameonbollywood              6270
Name: hashtags, dtype: int64